// AUTO-GENERATED by .rnstorybook/generate-stories.js. Do not edit manually.
// prettier-ignore-start
import React from 'react';

import type { Meta, StoryObj } from '@storybook/react-native';

import * as Components from '@studio/ui/native';
import {
  storyExamples,
  storyMeta,
} from '@studio/ui/native/common/badge.examples';

// prettier-ignore-end

const componentName = storyMeta.componentName ?? 'common/badge.examples';
const Component =
  (Components as Record<string, React.ComponentType<unknown>>)[componentName] ??
  (() => null);

const meta: Meta<typeof Component> = {
  title: storyMeta.title ?? 'auto/common/badge.examples',
  component: Component,
  decorators: storyMeta.decorators,
  parameters: storyMeta.parameters,
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Neutral: Story = {
  ...storyExamples['Neutral'],
};

export const Info: Story = {
  ...storyExamples['Info'],
};

export const Success: Story = {
  ...storyExamples['Success'],
};

export const Warning: Story = {
  ...storyExamples['Warning'],
};

export const Danger: Story = {
  ...storyExamples['Danger'],
};

export const LongLabel: Story = {
  ...storyExamples['LongLabel'],
};
