// AUTO-GENERATED by .rnstorybook/generate-stories.js. Do not edit manually.
// prettier-ignore-start
import React from 'react';

import type { Meta, StoryObj } from '@storybook/react-native';

import * as Components from '@studio/ui/native';
import {
  storyExamples,
  storyMeta,
} from '@studio/ui/native/common/button.examples';

// prettier-ignore-end

const componentName = storyMeta.componentName ?? 'common/button.examples';
const Component =
  (Components as Record<string, React.ComponentType<unknown>>)[componentName] ??
  (() => null);

const meta: Meta<typeof Component> = {
  title: storyMeta.title ?? 'auto/common/button.examples',
  component: Component,
  decorators: storyMeta.decorators,
  parameters: storyMeta.parameters,
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Solid: Story = {
  ...storyExamples['Solid'],
};

export const Outline: Story = {
  ...storyExamples['Outline'],
};

export const Small: Story = {
  ...storyExamples['Small'],
};

export const Large: Story = {
  ...storyExamples['Large'],
};

export const Disabled: Story = {
  ...storyExamples['Disabled'],
};

export const CompactOutline: Story = {
  ...storyExamples['CompactOutline'],
};

export const WithCustomTextStyle: Story = {
  ...storyExamples['WithCustomTextStyle'],
};
