// AUTO-GENERATED by .rnstorybook/generate-stories.js. Do not edit manually.
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Components from '@studio/ui/native';
import {
  storyExamples,
  storyMeta,
} from '@studio/ui/native/common/card.examples';

const componentName = storyMeta.componentName ?? 'common/card.examples';
const Component =
  (Components as Record<string, React.ComponentType<unknown>>)[componentName] ??
  (() => null);

const meta: Meta<typeof Component> = {
  title: storyMeta.title ?? 'auto/common/card.examples',
  component: Component,
  decorators: storyMeta.decorators,
  parameters: storyMeta.parameters,
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Basic: Story = {
  ...storyExamples['Basic'],
};

export const WithFooter: Story = {
  ...storyExamples['WithFooter'],
};

export const NoHeader: Story = {
  ...storyExamples['NoHeader'],
};

export const LongContent: Story = {
  ...storyExamples['LongContent'],
};
