// AUTO-GENERATED by .rnstorybook/generate-stories.js. Do not edit manually.
// prettier-ignore-start
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Components from '@studio/ui/native';
import {
  storyExamples,
  storyMeta,
} from '@studio/ui/native/common/text-field.examples';
// prettier-ignore-end

const componentName = storyMeta.componentName ?? 'common/text-field.examples';
const Component =
  (Components as Record<string, React.ComponentType<unknown>>)[componentName] ??
  (() => null);

const meta: Meta<typeof Component> = {
  title: 'auto/TextField (native)',
  component: Component,
  decorators: storyMeta.decorators,
  parameters: storyMeta.parameters,
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  ...storyExamples['Default'],
};

export const Error: Story = {
  ...storyExamples['Error'],
};

export const Disabled: Story = {
  ...storyExamples['Disabled'],
};

export const Password: Story = {
  ...storyExamples['Password'],
};

export const Multiline: Story = {
  ...storyExamples['Multiline'],
};
