// AUTO-GENERATED by .rnstorybook/generate-stories.js. Do not edit manually.
import React from 'react';

import type { Meta, StoryObj } from '@storybook/react-native';

import * as Components from '@studio/ui/native';
import {
  storyExamples,
  storyMeta,
} from '@studio/ui/src/native/common/toggle-row.examples';

const componentName = storyMeta.componentName ?? 'common/toggle-row.examples';
const Component =
  (Components as Record<string, React.ComponentType<any>>)[componentName] ??
  (() => null);

const meta: Meta<typeof Component> = {
  title: storyMeta.title ?? 'auto/common/toggle-row.examples',
  component: Component,
  decorators: storyMeta.decorators,
  parameters: storyMeta.parameters,
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  ...storyExamples['Default'],
};

export const Disabled: Story = {
  ...storyExamples['Disabled'],
};

export const LongCopy: Story = {
  ...storyExamples['LongCopy'],
};

export const OffByDefault: Story = {
  ...storyExamples['OffByDefault'],
};
