// AUTO-GENERATED by .rnstorybook/generate-stories.js. Do not edit manually.
import React from 'react';

import type { Meta, StoryObj } from '@storybook/react-native';

import * as Components from '@studio/ui/native';
import {
  storyExamples,
  storyMeta,
} from '@studio/ui/src/native/screen/tasks.examples';

const componentName = storyMeta.componentName ?? 'screen/tasks.examples';
const Component =
  (Components as Record<string, React.ComponentType<any>>)[componentName] ??
  (() => null);

const meta: Meta<typeof Component> = {
  title: storyMeta.title ?? 'auto/screen/tasks.examples',
  component: Component,
  decorators: storyMeta.decorators,
  parameters: storyMeta.parameters,
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Interactive: Story = {
  ...storyExamples['Interactive'],
};

export const WithControls: Story = {
  ...storyExamples['WithControls'],
};
